<h2>Rechten</h2>

<p>
	<a href="<?php echo $this->url(array(
			'action' => 'add'
		))?>">Rechten toevoegen</a>
</p>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th>Role</th>
			<th>Module</th>
			<th>Controller</th>
			<th>Action</th>
			<th>Type</th>
			<th width=1></th>
			<th width=1></th>
		</tr>
	</thead>
	<?php
	$i = 0;
	foreach ( $this->rights as $right ): ?>
	<tr class="<?php echo $i++ % 2 == 0 ? "even" : "odd" ?>">
		<td class="role"><?php echo $right['role']?></td>
		<td class="module"><?php echo $right['module']?></td>
		<td class="controller"><?php echo $right['controller']?></td>
		<td class="action"><?php echo $right['action']?></td>
		<td class="type"><?php echo $right['type']?></td>
		<td style="white-space: nowrap;">
			<a href="<?php echo $this->url( array( 'action' => 'edit' ) ) ?>" class="btn btn-mini">
				<i class="icon-pencil"></i>
			</a>
		</td>
		<td style="white-space: nowrap; text-align: center;">
			<a href="<?php echo $this->url( array( 'action' => 'delete' ) ) ?>" class="btn btn-mini btn-confirm" data-confirm-class="btn-warning">
				<i class="icon-remove"></i>
				<span class="txt-confirm">Sure?</span>
			</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>

<?php try{ echo $this->paginationControl($this->rights, 'Sliding', 'pagination.phtml'); } catch( Exception $e ) { print $e; } ?>
