<?php echo $this->doctype() . PHP_EOL ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php
		echo $this->headMeta() . PHP_EOL;
		echo $this->headTitle( 'Admin' ) . PHP_EOL;
		echo $this->headLink() . PHP_EOL;
		echo $this->headScript() . PHP_EOL;
	?>
</head>
<body>
	<div id="container" class="container-fluid">
		<header id="header" class="header">
			<h1>
				<a href="/admin">
					Dennis Claassen.nl <small>&mdash; Admin</small>
				</a>
			</h1>
		</header>
		
		<nav id="navigation" class="navigation">
			<?php 
				$branch = $this->navigation()
					->setRenderInvisible( true )
					->findActive( $this->navigation()->getContainer(), 1, 1 );

				if( count( $branch ) !== 0 && $branch['page']->hasChildren() )
				{
					$pages = $branch['page']->getPages();
					
					$subNav = new Zend_Navigation( $pages );
					echo $this->navigation()
						->menu( $subNav )
						->setRenderInvisible( true )
						->setUlClass( 'nav nav-tabs' )
						->setMinDepth( null )
						->setMaxDepth( 0 ); 
					
					$branch['page']->setPages( $pages );
				}
			?>
		</nav>
	
		<div id="breadcrumbs" class="breadcrumb">
			<?php 
				echo $this->navigation()
					->breadcrumbs()
					->setRenderInvisible( true )
					->setSeparator( ' <span class="divider">/</span> ' )
					->setMinDepth( null )
					->setMaxDepth( null ); ?>
		</div>
		
		<?php $branch = $this->navigation()
				->setRenderInvisible( true )
				->findActive( $this->navigation()->getContainer(), 2, 2 );

			if( count( $branch ) !== 0 && $branch['page']->hasChildren() ):
		?>

		<div class="row-fluid">
			<div class="span3">
				<nav id="side-navigation" class="well" style="padding: 8px 0;">		
						<?php
							$pages = $branch['page']->getPages();
							
							$subNav = new Zend_Navigation( $pages );
							echo $this->navigation()
								->menu( $subNav )
								->setRenderInvisible( false )
								->setPartial( 'side-navigation.phtml' )
								->setUlClass( 'nav nav-list' )
								->setMinDepth( null )
								->setMaxDepth( null );
						?>
				</nav>
			</div>

			<div id="content" class="content span9">
		<?php else: ?>
		<div class="row-fluid">
			<div id="content" class="span12">
		<?php endif;?>
        <?php echo $this->flashMessages() ?>

				<?php echo $this->layout()->content ?>
			</div>
		</div>
	
	</div>
</body>
</html>
