<?php echo $this->doctype() . PHP_EOL ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php
		echo $this->headMeta() . PHP_EOL;
		echo $this->headTitle() . PHP_EOL;
		echo $this->headLink() . PHP_EOL;
		echo $this->headScript() . PHP_EOL;
	?>
</head>
<body>
	<header class="header">
		<h1>
			<a href="/">
				Dennis Claassen.nl
			</a>
		</h1>
	</header>

	<nav class="main-navigation">
		<?php echo $this->navigation()
				->menu()
				->setUlClass( 'nav nav-tabs' )
				->setMinDepth( 1 )
				->setMaxDepth( 1 ); ?>
	</nav>

	<nav class="breadcrumb">
		<?php echo $this->navigation()
				->breadcrumbs()
				->setSeparator( ' <span class="divider">/</span> ' )
				->setRenderInvisible( true )
				->setMinDepth( null )
				->setMaxDepth( null ); ?>
	</nav>

	<?php  echo $this->layout()->content ?>

</body>
</html>