<?php echo $this->doctype() . PHP_EOL ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php
		echo $this->headMeta() . PHP_EOL;
		echo $this->headTitle() . PHP_EOL;
		echo $this->headLink() . PHP_EOL;
		echo $this->headScript() . PHP_EOL;
	?>
</head>
<body>
  <div id="fb-root"></div>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="//connect.facebook.net/nl_NL/all.js#xfbml=1";fjs.parentNode.insertBefore(js,fjs);}(document,"script","facebook-jssdk");</script>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  <script>window.___gcfg = {lang: 'nl'};!function(d,s){var js=d.createElement(s),fjs=d.getElementsByTagName(s)[0];js.async=true;js.src='https://apis.google.com/js/plusone.js';fjs.parentNode.insertBefore(js, fjs);}(document,'script');</script>

	<header>
		<h1>
			<a href="http://blog.<?php echo DOMAIN ?>">
				Dennis Claassen.nl <small>&mdash; Blog</small>
			</a>
		</h1>

    <div class="btn-toolbar social-icons">

      <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle social-facebook" data-toggle="dropdown" href="#">
          Facebook
        </a>
        <div class="dropdown-menu" style="text-align: center;">
          <div class="fb-like" data-href="http://www.dennisclaassen.nl" data-send="false" data-layout="box_count" data-width="100" data-show-faces="false"></div>
        </div>
      </div>

      <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle social-twitter" data-toggle="dropdown" href="#">
          Twitter
        </a>
        <div class="dropdown-menu" style="text-align: center;">
          <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.dennisclaassen.nl" data-via="declaassen" data-count="vertical"></a>
        </div>
      </div>

      <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle social-googleplus" data-toggle="dropdown" href="#">
          Google+
        </a>
        <div class="dropdown-menu" style="text-align: center;">
          <div class="g-plusone" data-size="tall" data-href="http://www.dennisclaassen.nl"></div>
        </div>
      </div>

      <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle social-linkedin" data-toggle="dropdown" href="#">
          LinkedIn
        </a>
        <div class="dropdown-menu" style="text-align: center;">
          <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
          <script type="IN/Share" data-counter="top"></script>
        </div>
    </div>
	</header>
	
	<nav class="main-navigation">
		<?php 
			$branch = $this->navigation()
				->setRenderInvisible( true )
				->findActive( $this->navigation()->getContainer(), 1, 1 );

			if( count( $branch ) !== 0 && $branch['page']->hasChildren() )
			{
				$pages = $branch['page']->getPages();
				
				$subNav = new Zend_Navigation( $pages );
				echo $this->navigation()
					->menu( $subNav )
					->setUlClass( 'nav nav-tabs' )
					->setMinDepth( null )
					->setMaxDepth( 0 );
				
				$branch['page']->setPages( $pages );
			}
		?>
	</nav>

	<nav class="breadcrumb">
		<?php echo $this->navigation( )
				->breadcrumbs()
				->setRenderInvisible( true )
				->setSeparator( ' <span class="divider">/</span> ' )
				->setMinDepth( null )
				->setMaxDepth( null ); ?>
	</nav>
	
	<?php echo $this->layout()->content ?>

</body>
</html>
