<section itemscope itemtype="http://schema.org/Person">
	<figure class="vcard thumbnail">
		<img src="/img/me.jpg" alt="" itemprop="image" />
		
		<figcaption class="caption">

			<header>
				<h1 itemprop="name">Dennis Claassen</h1>
				<h2 itemprop="jobTitle">Web Developer</h2>
			</header>
		
			<ul>
				<li>
					<a href="http://www.dennisclaassen.nl/" rel="me" itemprop="url">
						<i class="icon-globe"></i> www.dennisclaassen.nl
					</a>
				</li>
			
				<li>
					<a href="mailto:info@dennisclaassen.nl" itemprop="email">
						<i class="icon-envelope"></i> info@dennisclaassen.nl
					</a>
				</li>
			
				<li>
					<a href="http://twitter.com/declaassen" rel="me" itemprop="url">
						<i class="twitter-icon"></i> @declaassen
					</a>
				</li>
			</ul>
		</figcaption>
	</figure>
	
</section>

<section class="skills">
	<header>
		<h2>Skills</h2>
	</header>
	
	<article>
		<ul>
			<li>
				<abbr class="initialism">HTML5</abbr>
			</li>
			<li>
				<abbr class="initialism">CSS</abbr>
			</li>
			<li>
				JavaScript
			</li>
			<li>
				jQuery
			</li>
			<li>
				Flash
			</li>
			<li>
				ActionScript 3
			</li>
			<li>
				<abbr class="initialism">PHP</abbr>
			</li>
			<li>
				Zend Framework
			</li>
			<li>
				<abbr class="initialism">ASP.NET</abbr>
			</li>
			<li>
				<abbr class="initialism">SQL</abbr>
			</li>
		</ul>
	</article>
</section>


<section>
	<header>
		<h2>Experience</h2>
	</header>
	
	<article itemscope itemtype="http://schema.org/Organization">
		<h3>Web Developer</h3>
		<h4 itemprop="name">Uitzendbureau.nl</h4>
		<p>Mei 2011 - heden</p>
		
		<blockquote>
			<p itemprop="description">Uitzendbureau.nl is Nederlands grootste banensite voor uitzendwerk. Werkzoekenden vinden via Uitzendbureau.nl snel een leuke baan.</p>
		</blockquote>
		
		<!-- 
		<p>Bij Uitzendbureau.nl ....</p>
	 	-->
		
		<ul class="unstyled">
			<li>
				<a href="http://www.uitzendbureau.nl/" itemprop="url">
					<i class="icon-globe"></i> www.uitzendbureau.nl
				</a>
			</li>
		</ul>
		
	</article>
	
	<article itemscope itemtype="http://schema.org/Organization">
		<h3>Developer</h3>
		<h4 itemprop="name">Hogeschool van Arnhem en Nijmegen</h4>
		<p>Juli 2011 - januari 2012</p>
		
		<blockquote>
			<p itemprop="description">Interactive Storytelling for Flash</p>
			<small>FreeCoffee</small>
		</blockquote>
		
		<!-- 
		<p>Tijdens mijn studie aan de <abbr title="Hogeschool van Arnhem en Nijmegen">HAN</abbr> hebben wij met een projectgroep een applicatie ontwikkeld, waarmee interactieve verhalen gemaakt kunnen worden.</p>
		 -->
		 
	</article>
</section>

<section>
	<header>
		<h2>Education</h2>
	</header>
	
	<article itemscope itemtype="http://schema.org/EducationalOrganization">
		<h3 itemprop="name">Hogeschool van Arnhem en Nijmegen <small>Informatica en Communicatie Academie</small></h3>
		<h4>Communication &amp; Multimedia Design</h4>
		<p>September 2008 - heden</p>

		<address itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
			<span itemprop="streetAddress">Ruitenberglaan 26</span><br />
			<span itemprop="postalCode">6826 CC</span> <span itemprop="addressLocality">Arnhem</span>
		</address>
		
		<ul class="unstyled">
			<li>
				<a href="http://www.han.nl/" class="" itemprop="url">
					<i class="icon-globe"></i> www.han.nl
				</a>
			</li>
		</ul>
		</article>

</section>

<div class="well" itemscope itemtype="http://schema.org/Person">
	<ul class="thumbnails">
		<li>
			 <a rel="author" itemprop="url" href="https://plus.google.com/104282110032153413913" title="Google+" target="_blank">
			 	<img class="thumbnail" src="/img/glyphicons/glyphicons_362_google+_alt.png" width="32" height="32" alt="Google+" />
			 </a>
		</li>
		<li>
			 <a rel="me" itemprop="url" href="http://twitter.com/declaassen" title="Twitter" target="_blank">
			 	<img class="thumbnail" src="/img/glyphicons/glyphicons_392_twitter.png" width="32" height="32" alt="Twitter" />
			 </a>
		</li>
		<li>
			 <a rel="me" itemprop="url" href="http://www.linkedin.com/in/declaassen" title="LinkedIn" target="_blank">
			 	<img class="thumbnail" src="/img/glyphicons/glyphicons_377_linked_in.png" width="32" height="32" alt="LinkedIn" />
			 </a>
		</li>
	</ul>
</div>