<h2>Blog</h2>

<p>
	<a href="<?php echo $this->url( array( 'module' => 'blog', 'controller' => 'admin', 'action' => 'add' ), null, true ); ?>">Blog item toevoegen</a>
</p>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th>#</th>
			<th>Titel</th>
			<th>Datum</th>
			<th>Reacties</th>
			<th width=1></th>
			<th width=1></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach( $this->blogs as $blog): ?>
			<tr>
				<td><?php echo $blog->getId(); ?></td>
				<td><?php echo $blog->getTitle(); ?></td>
				<td><?php echo $blog->getCreatedOn(); ?></td>
				<td>0</td>
				<td style="white-space: nowrap;">
					<a href="<?php echo $this->url( array( 'action' => 'edit', 'id' => $blog->getId() ) ) ?>" class="btn btn-mini">
						<i class="icon-pencil"></i>
					</a>
					</td>

				<td style="white-space: nowrap; text-align: center;">
					<a href="<?php echo $this->url( array( 'action' => 'delete', 'id' => $blog->getId() ) ) ?>" class="btn btn-mini btn-confirm" data-confirm-class="btn-warning">
						<i class="icon-remove"></i>
						<span class="txt-confirm">Sure?</span>
					</a>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

