<h2>Navigatie</h2>

<p>
	<a href="<?php echo $this->url( array( 'action' => 'add' ) ); ?>">Pagina toevoegen</a>
</p>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th>Label</th>
			<th>URL</th>
			<th width=1></th>
			<th width=1></th>
		</tr>
	</thead>

	<?php echo $this->navigation()
		->menu()
		->setRenderInvisible( true )
		->renderPartial( $this->navigation()->getContainer(), 'navigation.phtml' ); ?>

</table>